#!/bin/dash

export HOME=/home/user

cd $HOME/services
perl -MTemplate -E'Template->new(ABSOLUTE=>1)->process(q(/home/user/offlineimaprc.tt), \%ENV) or die Template->error' > /home/user/.offlineimaprc
perl -MTemplate -E'Template->new(ABSOLUTE=>1)->process(q(/home/user/monitrc.tt), \%ENV) or die Template->error' > /home/user/.monitrc
chown user /opt/log /opt/var /home/user/.offlineimaprc /home/user/.monitrc -R
chmod 600 /home/user/.monitrc
exec 2>&1 sudo -u user runsvdir -P .
